<?php
namespace  widehaven\recaptchaBundle\type;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecaptchaSubmitType extends AbstractType {
    private $key;

    public function __construct($key)
    {
        $this->key =$key;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
           'mapped'=>false,


        ]);
       // parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
    public function getBlockPrefix()
    {
        return 'recaptcha_submit';
     //   return parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }
    public function getParent()
    {
        return TextType::class;
     //   return parent::getParent(); // TODO: Change the autogenerated stub
    }
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['key']=$this->key;
        $view->vars['label']=false;
        $view->vars['button']= $options['label'];

        //   parent::buildView($view, $form, $options); // TODO: Change the autogenerated stub
    }

}